#!/usr/bin/env bash

## #ddev-generated: If you want to edit and own this file, remove this line.
## Description: Launch a browser with Redis Insight
## Usage: redis-insight
## Example: "ddev redis-insight"

# Determine whether to use HTTP or HTTPS based on environment
PROTOCOL="HTTP"
if [ "${DDEV_PRIMARY_URL%://*}" != "http" ] && [ -z "${GITPOD_WORKSPACE_ID:-}" ] && [ "${CODESPACES:-}" != "true" ]; then
    PROTOCOL="HTTPS"
fi

# Fetch the appropriate port within the redis-insight container
DDEV_REDIS_INSIGHT_PORT=$(ddev exec -s redis-insight sh -c "printenv | grep -w ${PROTOCOL}_EXPOSE | cut -d '=' -f 2 | cut -d ':' -f 1")

if [ -z "$DDEV_REDIS_INSIGHT_PORT" ]; then
    echo "Error: Could not retrieve Redis Insight port."
    exit 1
fi

ddev launch :"$DDEV_REDIS_INSIGHT_PORT"
